### ISSUE TITLE
Snapshot request timeout when recording

### ISSUE THREAD

**Issue by chris-chensy** [twrecked/hass-aarlo#250]
When the camera is in the recording state, it seems any calls to request a snapshot during recording will fail. I'm not sure if this is expected behavior or something wrong. I'm using the build .17 with the updated recording call for more than 30 sec. 

Before the update, I was able to request a snapshot during recording/streaming. Basically, I want to call the service 'image_processing.**scan**' during recording. If no person is detected, I would stop recording manually. But now I am no longer able to do so... The image used in '.scan' was not updated.

**Comment by twrecked** [comment]
The camera state machine in 0.6 isn't too good and it gets easily confused if you try to do several things at the same time.

I'd already been working on tidying this up in the 0.7 stream and this functionality is already working 0.7.0-alpha2.

So; good news, I have a fix; bad news, it's going to be in 0.7 only because it's too much work to bring back to 0.6.

I'll create 0.7.0-alpha.2 release later and you can try installing it from HACS, I believe you need to allow pre-releases.

**Comment by twrecked** [comment]
I'm going to close this for now.

0.7 is working much better (if I say so myself!). If something isn't working when 0.7 comes out feel free to re-open this issue.

**Comment by chris-chensy** [comment]
I have updated it to the build .19.1. It seems requesting a snapshot during recording is still problematic. The snapshot wasn't taken after the recording finished. Now the camera state is stuck in taking snapshot forever (no snapshot updated). My device is arlo ultra.
