### ISSUE TITLE
Assign to its own Aarlo.yaml

### ISSUE THREAD

**Issue by tmmedic20** [twrecked/hass-aarlo#379]
Not really an issue:

Being very new to Home Assistant im fumbling my way through the setup of Aarlo.

I am able to get everything configured in the configuartion.yaml

but being the OCD person I am, I prefer to move things to their own xxx.yaml files like groups/secrets/lights/scenes  etc etc

I have tried every way possible to format the file and always get a configuration error.

If i add 

aarlo: !include aarlo.yaml 

should the format be as follow:

username: !secret aarlo_usr
  password: !secret aarlo_pwd
  refresh_devices_every: 2
  stream_timeout: 120
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    trigger_time: 30
    alarm_volume: 8
camera:
  - platform: aarlo
binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding
    - connectivity
sensor:
  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
    - temperature
    - humidity
media_player:
  - platform: aarlo

My apologies if this is not the proper place to post this,  new to git hub too!

**Comment by twrecked** [comment]
I don't have anything to do with the configuration files, Home Assistant has already processed them by the time they get to me. 

But I'm pretty sure you won't be able to get `aarlo` configuration into a single file because each file can only only contain the same type of object - lights or switches or camera or...

[This](https://www.home-assistant.io/docs/configuration/splitting_configuration/) explains how to split up the config and [this](https://www.home-assistant.io/cookbook/#example-configurationyaml) has some good examples of user configuration splitting that might help.

**Comment by jesserockz** [comment]
@tmmedic20 If you are serious about splitting your configuration then you should already have found [packages](https://www.home-assistant.io/docs/configuration/packages/)

**Comment by tmmedic20** [comment]
> @tmmedic20 If you are serious about splitting your configuration then you should already have found [packages](https://www.home-assistant.io/docs/configuration/packages/)

I had not found that yet! That is great though thank you.  Only been messing with HA for a few weeks.

**Comment by twrecked** [comment]
I can't change this; has to be handled by another package.
