### ISSUE TITLE
Dashboard card does not update with current mode

### ISSUE THREAD

**Issue by dugancom** [twrecked/hass-aarlo#604]
Having a similar issue to #286 , the dashboard card has stopped showing the correct status after a mode change. The mode does change, but the dashboard only shows the correct status after a restart.

**Comment by Srki82** [comment]
sam issue here... mode updates after HA restart

**Comment by tobpet** [comment]
Same here.

**Comment by twrecked** [comment]
Can you try changing the backend to sse, see here:

https://github.com/twrecked/hass-aarlo#missing-events

**Comment by Srki82** [comment]
> Can you try changing the backend to sse, see here:
> 
> https://github.com/twrecked/hass-aarlo#missing-events

I have no problems changing the modes... I can see in the Arlo app that it changes. I can also see recorded videos, take snapshots etc. The problem is with the dashboard card where you change the modes. If I press Arm Away I can see in the arlo app that it does change but  it should in HA dashboard card give me the opportunity to disarm the arlo like it did before... now that doesn't show up until I restart the HA completely. After restart of HA, I can see the current and correct mode and I can choose to disarm and it works to disarm. 
I have tried to add the line **backend: sse** in the configuration file but that did not change anything.

**Comment by tobpet** [comment]
> Can you try changing the backend to sse, see here:
> 
> https://github.com/twrecked/hass-aarlo#missing-events

I have this line in config.
Status is updated after reboot and a short period after.
After some time, status is not updated anymore.

**Comment by dugancom** [comment]
Adding the Server Side Events in my config as @twrecked mentioned fixed it for me.

aarlo:
  ..your current config..
  backend: sse

**Comment by Srki82** [comment]
> Adding the Server Side Events in my config as @twrecked mentioned fixed it for me.
> 
> aarlo: ..your current config.. backend: sse
> 
> Thanks!

Hi,
Sorry but where exactly do you enter that? I put that line in my configuration.yaml file and apparently it's incorrect. The server cannot restart. It gives me the following error: 

_Invalid config for [aarlo]: [backend] is an invalid option for [aarlo]. Check: aarlo->aarlo->backend. (See /config/configuration.yaml, line 78)._

This is the extract from my configuration.yaml file which prohibits me to restart the HA:

#Arlo integration
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120 
  tfa_host: imap.gmail.com
  tfa_username: xxxxxxxxxxx
  tfa_password: xxxxxxxxxxx
  backend: sse

**Comment by dugancom** [comment]
That looks correct to me.  

What version of Aarlo are you running?  Mine is 
v0.7.2b8.3

**Comment by Srki82** [comment]
> That looks correct to me.  
> 
> 
> 
> What version of Aarlo are you running?  Mine is 
> 
> v0.7.2b8.3
> 
> 

I also have v0.7.2b8.3

**Comment by twrecked** [comment]
Sorry for the delay getting back. 

@Srki82 It might have been a tab/spaces issue. Glad it's working now.
