### ISSUE TITLE
New Arlo Secure App (v4) Compatability?

### ISSUE THREAD

**Issue by JeffSteinbok** [twrecked/hass-aarlo#677]
My ArloSecure iOS app just updated to the new v4 UX which has a completely different automation system.   Since that update, it seems that I can't get or set alarm state from HA.  Looking at the logs, it seems to still see my old modes or something, which don't exist anymore.  I see nothing in the logs for the new mode names:
- Arm Away
- Arm Home
- Standby

Any thoughts on this?

2022-12-23 21:18:58.696 DEBUG (ArloBackgroundWorker) [pyaarlo] mode2<=M=>Outdoor Armed
2022-12-23 21:18:58.696 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A082037LA11CA/modeIdToName/mode2=Outdoor Armed
2022-12-23 21:18:58.696 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A082037LA11CA/modeNameToId/outdoor armed=mode2
2022-12-23 21:18:58.696 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A082037LA11CA/modeIsSchedule/outdoor armed=False
2022-12-23 21:18:58.696 DEBUG (ArloBackgroundWorker) [pyaarlo] mode3<=M=>Outdoor & Downstairs Armed
2022-12-23 21:18:58.696 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A082037LA11CA/modeIdToName/mode3=Outdoor & Downstairs Armed
2022-12-23 21:18:58.696 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A082037LA11CA/modeNameToId/outdoor & downstairs armed=mode3
2022-12-23 21:18:58.696 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A082037LA11CA/modeIsSchedule/outdoor & downstairs armed=False

**Comment by JeffSteinbok** [comment]
I took a fork of this repo and I'm making progress getting this to work.  The API seems reasonably straight-forward. I'm not sure I'll have time to totally cleanly factor it out right, but I'll definitely share any progress.

**Comment by twrecked** [comment]
Thanks for looking into this. Mine is still working for me here but I'll play around with it some more today.

What base stations do you have?

**Comment by JeffSteinbok** [comment]
Doesn't surprise me that it's still working for you.  They changed the Arlo app and APIs, but you have to "opt in" to the new experience for now.  Eventually they will force it on all people.  To opt in for now, you can try to add a new device, select "Security System" and it will prompt you to upgrade.  Has a whole new automations system which really sucks, so I wanted to use HA to do it all for me.

More info here:  https://kb.arlo.com/000062797/What-is-new-in-the-Arlo-Secure-App-4-0

The new App experience uses all new APIs which I'm trying to sort out:

- You need to get a location Id 
- You need to get a revision id
- Then instead of parsing the schedule, you just need to get it's current mode from one of the 3 fixed (you can't add new ones) modes.
- Appears you can get/set modes as follows:

curl $'https://myapi.arlo.com/hmsweb/automation/v3/activeMode?locationId=xxxxxxxx-343e-489e-a77d-4c8c2776681c' \
  -X 'PUT' \
  -H 'authority: myapi.arlo.com' \
  -H 'accept: application/json' \
  -H 'auth-version: 2' \
  -H 'content-type: application/json; charset=utf-8' \
  -H 'x-user-device-id: SNPDG-336-xxxxxxx' \
  --data-raw '{"mode":"armHome"}' \
  --compressed

Seems that the camera APIs still work as before.  I'm thinking to make a v3 on base.py that knows this API sequence may be the easiest. Not sure how to auto-detect this though, or maybe can pass it in somehow in the HA config.

Couple things I don't follow as I'm new at this an Python:

- How do you change the log level if you have a script like the below?
- How do you pass parameters from the HA config.yaml to the integration?


from pyaarlo import PyArlo
arlo = PyArlo(username='aaaa@gmail.com', password='xxxx', tfa_type='EMAIL',tfa_source='console')
arlo.base_stations
print(arlo.base_stations[0].mode)

**Comment by twrecked** [comment]
That explains a lot. I'm loathed to upgrade anything on my Arlo system because right now it works and I'm grandfathered into the old payment plan  which is much cheaper.  _I just checked, I'm not sure it is much cheaper anymore, the unlimited plan seems more reasonable than I remember, I'll have more time to look in the new year._

You can change log levels with this code but you have to run it before you call `PyArlo`. Adjust `level=` as needed, there is `logging.INFO` and `logging.ERROR` I think.

```
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
```

And you have to pass the parameters in by hand.  Take a look [around here](https://github.com/twrecked/hass-aarlo/blob/cacf01a9d1434add0f69ff5fc28725799e39c77a/custom_components/aarlo/__init__.py#L302).

**Comment by JeffSteinbok** [comment]
I don't blame you. The unlimited plan is reasonable now I think.
They will eventually force everyone into the new app experience I think, can't imagine them wanting to support multiple.

I'm making some progress, the thing I don't follow yet is how the callbacks work when Arlo changes the mode; how does it update your library.  I'm going to need to play around with that some more.

**Comment by twrecked** [comment]
There is an event handler that connects to an `SSE` or `MQTT` back end, it parses out the responses, stores the values and  calls and registered callbacks. `backend.py` has most of  this code.

**Comment by JeffSteinbok** [comment]
Ok, help me out here.
How do you use the Chrome/Edge DevTools to trace the structure of the callbacks here from SSE or MQTT?  Trying to see how the notification of mode changes gets pushed to the website or app.

**Comment by twrecked** [comment]
That's where it gets fun.  You use the `Network` tab to work out what you need to send in. You click the button on the web page and see what gets added to the network list, you can click on it and see the contents. If the reply is immediate it will be part of the network packet. If it's not immediate, how to get the reply is more interesting, it depends on the back end:

###  `SSE`
The _URL_ you are looking for will end in `subscribe`. But _Chrome_ will not display the event stream traffic, I think this is a bug. (And nor will _FireFox_.) You have to add the request code into _PyArlo_ and see what comes back, `verbose_debug` and `packet_dump` will help you get the information you need.

### `MQTT`
This was nicer. I can't tell you exactly what to look for here because I only had _MQTT_ working for a week while I borrowed a camera. But I do remember _Chrome_ would display the _MQTT_ packets correctly. Look for a _URL_ ending in `mqtt` and you should see responses appearing on that.

**Comment by JeffSteinbok** [comment]
Oh boy. This is gonna be fun. Thanks for the pointers. 

I’ll see what I can figure out.

**Comment by twrecked** [comment]
I can't do anything for a day or two (or more like three) but I'm definitely going to look into changing my plan and then maybe moving to version 4 to help out. You can also make changes from the App and you should see events coming into _PyArlo_.

The new secure plan is slightly more expensive but I get to add my 11th camera for free so that's nice. I might even think about upgrading some of the cameras later.

**Comment by JeffSteinbok** [comment]
First cut at getting **something** to work:  
https://github.com/JeffSteinbok/hass-aarlo/commit/2c2ad9142c180b53d75e173931b6b74ca798ae5f

LocationId is still hard-coded in this, I need to fix that ASAP.

**Comment by JeffSteinbok** [comment]
One thing I'm quite puzzled on and I can't figure out from Chrome either is that it doesn't appear Arlo sends anything on the SSE stream about the location update; it seems to send an update for each device and base station.  Only thing I can think of off-hand is once we get an update to one of them, pull the location active mode proactively.  It seems a bit hacky, and the only thing prevent spamming would be the check you have to not check too frequently.

Anything you think I could be missing?  Subscribe link seems the same.

**Comment by JeffSteinbok** [comment]
Got location mode setting working:  https://github.com/JeffSteinbok/hass-aarlo/commit/98655dab32a4e091d1a2c921bb91126ba91e6379

Still need to figure out how to do the alarm panel integrations while supporting both versions of the APIs at once.  I have no idea how sirens would work in the new model either, so I was just thinking best to register **more alarm panels** so we have one per base and one per location for now.  It's a bit ugly though.

Any thoughts?

**Comment by JeffSteinbok** [comment]
https://github.com/JeffSteinbok/hass-aarlo/tree/version-0.7.x
Basic HA integration works! Still quite dirty.  I can clean up and integrate into your v7 branch if you want, or you can copy what you want.

![image](https://user-images.githubusercontent.com/7330767/210913267-84817931-c1fb-46af-b134-98651b283d55.png)

**Comment by twrecked** [comment]
Thanks for the update. I'm actually away for a few days - in an unusually warm New York City - but will be back this weekend. I'll take a look on Sunday with any luck. 

I'm thinking of moving to version 8 but it's quite similar to 7 I just moved the pyaarlo piece to pypi.

**Comment by JeffSteinbok** [comment]
Sounds good.  I can also move the changes to v0.8 and do a PR into your repo.
There are a few other things I wanted to do:

- A bit more Python typing to make it easier to find errors
- Create a base class for ArloEntities (name tbd?) to base Location and Device off of.  
- Something to do with location names, need to figure out a more friendly view in HA

**Comment by JeffSteinbok** [comment]
Woohoo!  It works.  I'm now running my version on my HA instance.
Using HA templates and presence stuff.  Tracking kids phones via Unifi too.  Love it.
Disabled all my Arlo automations

![image](https://user-images.githubusercontent.com/7330767/211123241-cca6bd65-cafa-4a56-b5d0-33ac079cb44c.png)

**Comment by twrecked** [comment]
That's awesome. And thinking about it, I've never used the _Arlo_ automations, I've always tracked presence through Home Assistant and had that make the changes.

I have to finish up some work on the virtual piece I maintain so I'll start working on the _Arlo_ piece this week. I also bought some Pro 4 cameras so I want to see how well they integrate.  Does the `location` work like a group controller? Now I have 3 pro 4 cameras I suddenly have 7 base stations and I can see turning them all on and off could be error prone.

And you can hook _Unifi_ into the system, how did I miss that? I bought a couple of their devices this time last year and never thought about integrating them.

**Comment by JeffSteinbok** [comment]
The Arlo stuff used to be buggy, and with this v4 thing, it's just useless.  HA is so much more flexible and debuggable, love it so far.  

Not sure what you mean by "group controller"; I assume you can have multiple base stations or non-hub cameras in a location and control them all by setting a location mode.  Curious what you find.  I suspect you can just set it once and have it work.  I have all my 7 cameras tied to my hub, but now I guess I don't need to. My Unifi network has much better wifi coverage than my hub.

Be careful with the Unifi stuff; if you enable too much, it will bloat your HA history DB.  But I use that for kids, and my wife and I have the app installed.

**Comment by kneeboy03** [comment]
I am having the same issues after upgrading to v4 US. How did you get it work with the new modes?

**Comment by chicknlil** [comment]
Thanks @JeffSteinbok for your fork. I was on v4 and have been since I got my battery operated camera, and my aarlo integration had stopped responding a few days ago (my TFA was "Push").  Using your fork and changing TFA to the email account got everything working again.  @twrecked , would you be so kind as to comment here when you've incorporated these changes into the main repo so I can migrate back to it?  Much appreciated to you both!

**Comment by JeffSteinbok** [comment]
@chicknlil  feel free to use my fork, but it's totally "AS IS" and somewhat hacky. 
@twrecked  - When you have a chance, let me know what you see for next steps?

**Comment by twrecked** [comment]
I'm going to take a look this week. Long story short, the upgrades to my home system took more time. Turns out my Hue hub was 2 years out of date and several of my switches needed re-syncing with the network. It's all looking better now.

My plan is to:
- take a look at the diffs
- make sure your fork works with my old API system
- make sure upgrading to `0.8` works fine
 
If `0.8` looks good then I'll look to merge your changes into `hass-aarlo` and `pyaarlo`. 

If `0.8` doesn't look so good, I'll merge them into `0.7` and work on the `0.8` changes.

I'm still trying to upgrade one of my _Arlo_ accounts to the new interface so I can test it better but it keeps complaining about the hub associated with that account.

**Comment by twrecked** [comment]
After all that, do you want to create a pull request for 0.7? It seems like there are several people with the new v4 api who would benefit from the change. I'll aim to get a release out shortly after approving the merge. 

As to the code; it seemed pretty straight forward and isolated, there are a few cosmetic things found by my editor I'd like to fix but nothing that can't wait until after the initial release.  To give you an idea, it complains about the brackets around this check. _This might seem overly picky but the plan is to move this back into _Home Assistant_ one day and they have pretty strict coding standards._

```python
        return (self.cfg.mode_api.lower() == "v3")
```


I can't get any one of my test systems to upgrade to v4 but I'll make a more concerted effort later this week. Which means I'll be able to test it as well.

For version 0.8 I've split out the _Home Assistant_ piece and the `pyaarlo` piece, the patch went into `pyaarlo` pretty easily and rather than having you duplicate the work I checked in the changes [into a v4-api branch](https://github.com/twrecked/pyaarlo/tree/v4-api), can you take a look at that? It's CLI only but you seem like your comfortable with that. 

If all goes well, I'll aim to patch _v0.8_ `hass-aarlo` and release a new `pyaarlo` next week.

**Comment by JeffSteinbok** [comment]
Sure, I'll do a PR.

For the v4 stuff; if you are in the US anyway, you should be able to upgrade by trying to add "Security System" or their newest camera.  You don't need to have it, just go through the wizard to add it.

**Comment by JeffSteinbok** [comment]
PR is in.

**Comment by twrecked** [comment]
It should be in the 0.7.3 release. Many thanks for doing this, it's really appreciated.

**Comment by JeffSteinbok** [comment]
Thanks!  My first GitHub PR not in my own repo!

**Comment by twrecked** [comment]
If you get a chance can you try this branch:
  https://github.com/twrecked/hass-aarlo/tree/0.7.x-location-updates

It includes a few tidy ups:
- events are now being directed to location instances
- I got rid of the alarm mode naming, I don't think it's needed because Arlo doesn't seem to let you change their names any more
- (per your idea) I created a `ArloSuper` base class for `ArloDevice` and `ArloLocation` (there is probably some more tidy up I can do here)
- change alarm entity naming convention to match the other components (this one might break your set up)
