### ISSUE TITLE
general-error=gaierror

### ISSUE THREAD

**Issue by zemerick1** [twrecked/hass-aarlo#849]
Version: 0.8.1a10

Continuously see the above error message in the log. Followed by `socket.gaierror: [Errno -2] Name does not resolve`

The only reference I saw to this error message is to enable backend: sse which I have done because I left my legacy config in place. 

I didn't see any clear install instructions so I just copied the latest release into custom_components, and left my legacy config in place. If that is incorrect, let me know.

`
# ARLO
aarlo:
  
username: !secret arlo_username
  password: !secret arlo_password
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: !secret gmail_username
  tfa_password: !secret gmail_app_password
  backend: sse
  `
  
  To add: I do not see the /config directory after the install, which I thought everything was supposed to be moved to.

**Comment by zemerick1** [comment]
Well, I don't know what happened, but I deleted the integration entry via the UI, and restarted HA. . things started populating. Super weird.

**Comment by twrecked** [comment]
I recommend HASS for the install. But you can find all the options here:
https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#installation

`/config` is the directory containing your `configuration.yaml` file, its name might be different on your machine. But that is the name used inside the _Home Assistant_ docker instance.

If you are using `0.8.1a10` then the legacy configuration isn't being used anymore, you need to look for a file called `aarlo.yaml` in the same directory as `configuration.yaml`. Change the config in there to affect your install.

Your install works now because you 
- changed your legacy config
- deleted the Integration 
- and restarted
- the system imported your now modified configuration and everything worked
