### ISSUE TITLE
Arm/Disarm on older Models without Basestation (ArloQ)

### ISSUE THREAD

**Issue by pasphi** [twrecked/hass-aarlo#887]
Hi, 
i have installed and setup your integration on HA running on a Raspberry 4. However, i can not use/find a setting to arm/disarm my old ArloQ camera which is running standalone without Basestation. 
On the camera it self i can't find a setting to arm/disarm and the Alarm-Panel does not work either. I can set the Alarm Panel but the changes do not reflect in the Arlo App and vice versa. 
Do i overlook something or is the integration only working with newer models running on a base station? 
I am getting the following Logs message from HA Core when changing the status (arm/disarm) within the Arlo App

`AttributeError: 'NoneType' object has no attribute 'lower' 2024-02-05 22:02:09.369 ERROR (ArloBackgroundWorker) [pyaarlo] unable to read mode, try forcing v2 2024-02-05 22:02:09.494 ERROR (ArloBackgroundWorker) [pyaarlo] job-error=AttributeError Traceback (most recent call last): File "/config/custom_components/aarlo/pyaarlo/background.py", line 35, in _run_next job["callback"](**job["args"]) File "/config/custom_components/aarlo/pyaarlo/base.py", line 168, in _event_handler self.update_mode() File "/config/custom_components/aarlo/pyaarlo/base.py", line 393, in update_mode self._set_mode_or_schedule(mode) File "/config/custom_components/aarlo/pyaarlo/base.py", line 135, in _set_mode_or_schedule self._save_and_do_callbacks(MODE_KEY, mode_name) File "/config/custom_components/aarlo/pyaarlo/super.py", line 77, in _save_and_do_callbacks self._do_callbacks(attr, value) File "/config/custom_components/aarlo/pyaarlo/super.py", line 70, in _do_callbacks cb(self, attr, value) File "/config/custom_components/aarlo/alarm_control_panel.py", line 241, in update_state self._state = self._get_state_from_ha(self._base.attribute(MODE_KEY)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/aarlo/alarm_control_panel.py", line 357, in _get_state_from_ha lmode = mode.lower() ^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'lower' 2024-02-05 22:04:28.639 ERROR (ArloBackgroundWorker) [pyaarlo] unable to read mode, try forcing v2`

**Comment by twrecked** [comment]
It should work with the Arlo Q, I knew of some people who were using them. Can we start by pasting in your config?

If you are on 0.7 I need both the main config and the alarm config.

**Comment by pasphi** [comment]
I am using v0.7.4.2 from HACS.

The config is as follows
`aarlo:
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: ***
  tfa_password: ***
  username: ***
  password: ***
  backend: sse

camera:
  - platform: aarlo

binary_sensor:
  - platform: aarlo
    monitored_conditions:
      - motion

alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home`

**Comment by twrecked** [comment]
@pasphi  You're the second person seeing this. Can you [capture](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#very-verbose-debug) and [upload](https://github.com/twrecked/hass-aarlo?tab=readme-ov-file#hiding-sensitive-data) some verbose logs for me?

**Comment by pasphi** [comment]
Hey, yes.
I think i have done it correctly? Encrypted File attached.
[home-assistant-log-encrypted.txt](https://github.com/twrecked/hass-aarlo/files/14313751/home-assistant-log-encrypted.txt)

**Comment by twrecked** [comment]
They were great. I can see the attempts to change to mode going in and not working.

I need some capture from earlier in the log. Can you look for some test that contains `=M=`, this is the code that sets up the mappings from Arlo modes to Home Assistant modes. For some reason the code is not recognising your home and away settings.

And one final question, are you on the new location based interface?

**Comment by pasphi** [comment]
Just restarted home assistant with verbose for Aarlo on and changed state of the camera in the Arlo app and then tried as well in the alarm panel of your integration. However, nowhere in the logs does `=M=` show up?

**Comment by twrecked** [comment]
Are you seeing this `V3Modes - None on BaseStation`?

**Comment by pasphi** [comment]
No `V3Modes` either. If this is related to a BaseStation from Arlo, that might explain the issue. The ArloQ i am using does not have/require a Basestation but is fully standalone.

**Comment by twrecked** [comment]
We should still treat it as a base station so should ask it for modes and so on.

Can you send the debug from earlier in the startup? I'll take a look.

**Comment by pasphi** [comment]
Yep, please find it attached.
[home-assistant-log-encrypted.txt](https://github.com/twrecked/hass-aarlo/files/14314123/home-assistant-log-encrypted.txt)

**Comment by twrecked** [comment]
If you have one camera or don't mind testing can you try adding this to your configuration:

```yaml
aarlo:
  .. usual stuff
  mode_api: v2
```

This forces it to use the newer API.

I'll keep looking.

**Comment by pasphi** [comment]
Hi, can confirm that after adding 'mode_api: v2' to the configuration i can both deactivate and activate the camera (disarmed and away modes) from the alarm panel and the change reflects on the app and vice versa! That solved the issue for me, thank you very much!

**Comment by cswinney22** [comment]
Hey Steve,
I've been playing with this on my end and here's the shorthand. For ease of reading (because I have a ton of smart devices that are reporting too), I either deleted logs or saved them as log.1, log.2 etc. log.3 has all the confirmations of proper mode, arm / disarm mode names etc, and connection successes. 
When on API mode set to auto, I get the no modes for basestations errors and not real obvious confirmations of the commands sending successfully etc.
If I set to V2 as you suggested to passpi, I DO start seeing successful connection, proper mode names and when I send commands to arm or disarm, I've been able to set the names incorrectly to receive a 'mode xxxx not recognized' and setting it to the proper naming based on my captured packets when logged in via web browser to arlo, I see that the command is recognized and sent successfully, but the modes never visibly change in the HA card. I see the following message:
backend: unhandled response automation/active - {'to': 'https://vzweb26-prod.ar.arlo.com', 'from': 'A47E277RECA2D'
'A47E277RECA2D' is a spotlight Arlo camera (model ID:VMC2030A). The camera reports as on, connected, wifi, etc. So, it's pulling all the data, but the response error might be something to do with the reason it's not adjusting in the card. 
I have not yet monitored the web-browser arlo response when the arm/disarm is sent to my devices though.
What I also noticed, that you might have already seen, is the mode0, mode1, etc stuff showing statuses like armed and disarmed. They don't match the naming that sends when arming and disarming (armHome, armAway, standby). In you readme, you say the arlo system doesn't have names for stuff like home or night modes. I'm wondering if this has changed since you wronte that, because I don't remember ever setting up any custom modes. Standby, Arm Home, Arm Away have always been around as far as I'm aware. These modes are not renamable and I can't add new modes (using the mobile app). They still group all cameras together to set rules for each of them on how they behave and such while that mode is active. I think automations also still work as they always have but I haven't had arlo for more than a year. (I had the base station editions when they were new, but returned them after a day or less.

Please let me know if this helps, if you need any info or logs, or if you want to do anything else. I've glanced at small portions of the code, but haven't messed with anything yet. It will take me a bit to read all the code, if I do that, but it's pretty clean (natually). So, before I went playing, I wanted to see if the above helped at all.

**Comment by twrecked** [comment]
Reopen for @cswinney22 

@cswinney22 Do you have the new Arlo interface? The one based around locations?

**Comment by cswinney22** [comment]
> Reopen for @cswinney22
> 
> @cswinney22 Do you have the new Arlo interface? The one based around locations? Because that's where armHome is used.
> 
> In which case you can't arm or disarm an individual camera, you have to arm or disarm the location.

I do have the newest pull 0.8.1. That would make sense then. I didn't notice that anywhere in the docs.
I'm locked in V2 right now. I'll switch back to auto (v3) because I don't see any location entities in V2.  Will update shortly.

**Comment by cswinney22** [comment]
> Reopen for @cswinney22
> 
> @cswinney22 Do you have the new Arlo interface? The one based around locations? Because that's where armHome is used.
> 
> In which case you can't arm or disarm an individual camera, you have to arm or disarm the location.

Hey @twrecked,
I've reloaded in auto which detects as V3. I re-searched the documentation and I'm overlooking something obvious I think. I don't see mention of location setup, but I think that's because it's supposed to be obvious.
When I read the logs after the reboot, I see a few attempts to identify locations available and to no avail. It shows no locations. It tried to login and got denied by cloudflare, it rotated and got past it, and then it queried for locations but I think the response was bad.

supportsMultiLocation is True and confirmed in the logs. I think the page is giving a 404 error and not returning anything that can be interpreted by Pyaarlo. Here's the lines I saw that are related. I'm going to see if I maybe forgot to set default locations or something, but I don't think that's the cause here.

`2024-02-19 11:10:26.133 DEBUG (SyncWorker_1) [pyaarlo] backend: request-url=https://my.arlo.com/hmsdevicemanagement/users/4FRRHW-336-63261314/locations?eventId=FE!156cd49b-a9e0-4a5c-b1b3-84b0a1fd5b52&time=1708369826133
2024-02-19 11:10:26.133 DEBUG (SyncWorker_1) [pyaarlo] backend: request-params=
{}
2024-02-19 11:10:26.133 DEBUG (SyncWorker_1) [pyaarlo] backend: request-headers=
{'x-transaction-id': 'FE!156cd49b-a9e0-4a5c-b1b3-84b0a1fd5b52'}
2024-02-19 11:10:26.333 WARNING (SyncWorker_1) [pyaarlo] body-error=JSONDecodeError
2024-02-19 11:10:26.333 DEBUG (SyncWorker_1) [pyaarlo] request-text=<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><script>(function(){var js = "window['__CF$cv$params']={r:'8580cf55697e0fe8',t:'MTcwODM2OTgyNi4zMTkwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body></html>
2024-02-19 11:10:26.333 WARNING (SyncWorker_1) [pyaarlo] No locations returned from /hmsdevicemanagement/users/4FRRHW-336-63261314/locations
2024-02-19 11:10:26.334 DEBUG (SyncWorker_1) [pyaarlo] locations=[]`

**Comment by twrecked** [comment]
Just to clarify, when I'm talking about _locations_ I'm talking about the change _Arlo_ made about 6 months ago that stopped people arming and disarming individual camera. `hass-aarlo` should support both the old and new methods. The problem is I don't have the location setup so I rely on people helping me with this.

One thing to to do is to login into the [Arlo website](https://my.arlo.com/#/home) with both your _Arlo_ accounts - your main one and then your _Home Assistant_ to make sure everything looks ok there.

**Comment by cswinney22** [comment]
> Just to clarify, when I'm talking about _locations_ I'm talking about the change _Arlo_ made about 6 months ago that stopped people arming and disarming individual camera. `hass-aarlo` should support both the old and new methods. The problem is I don't have the location setup so I rely on people helping me with this.
> 
> One thing to to do is to login into the [Arlo website](https://my.arlo.com/#/home) with both your _Arlo_ accounts - your main one and then your _Home Assistant_ to make sure everything looks ok there.

Yeah it all looks fine from what I can see. The only difference I see is what was discussed in other tickets. My haas Arlo account shows the 'home' location shared from my main account and a home location that is setup by default. I renamed it to just '.' so I thought maybe that was causing an issue. So, I renamed it to 'NotHome' and it's still not returning location info from what I can see. I DO have the new version of haas-aarlo and I went through all the mobile app updates and such, because I had the issue others were reporting where my new haas arlo account couldn't see any devices until I updated the mobile app and set location names. I can see all cameras from both user accounts.
I've tried running get/post intercepts and injecting tokens in then copying the web address that is being pushed from the integration:
myarlo.com/hmsweb/users/emergency/locations
before I inject the token, I was getting failed and reason: no valid token. After I inject the token, I get success but response is empty just like in the logs. I did not get any 404 pages or anything like that. So, may be a red herring. I just think the API isn't returning the locations as expected perhaps. So, I can't interact with the locations via entities. Nothing shows as hidden or disabled for me to enable either.

**Comment by twrecked** [comment]
Do you set the host in your config? Can you remove it?

**Comment by cswinney22** [comment]
> Do you set the host in your config? Can you remove it?

I do. I removed it and rebooted. I see it try a couple location paths.
https://my.arlo.com/hmsweb/users/emergency/locations
`2024-02-19 12:05:06.265 DEBUG (SyncWorker_5) [pyaarlo] backend: request-params=
{}
2024-02-19 12:05:06.266 DEBUG (SyncWorker_5) [pyaarlo] backend: request-headers=
{'x-transaction-id': 'FE!97178943-1d6a-415a-a687-282db10667f3'}
2024-02-19 12:05:06.461 DEBUG (SyncWorker_5) [pyaarlo] backend: request-body=
{'data': [], 'success': True}`

https://my.arlo.com/hmsdevicemanagement/users/4FRRHW-336-63261314/locations
`2024-02-19 12:05:06.462 DEBUG (SyncWorker_5) [pyaarlo] backend: request-params=
{}
2024-02-19 12:05:06.462 DEBUG (SyncWorker_5) [pyaarlo] backend: request-headers=
{'x-transaction-id': 'FE!f2ea1893-0425-4950-94de-2266da4ab448'}
2024-02-19 12:05:06.663 WARNING (SyncWorker_5) [pyaarlo] body-error=JSONDecodeError
2024-02-19 12:05:06.663 DEBUG (SyncWorker_5) [pyaarlo] request-text=<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><script>(function(){var js = "window['__CF$cv$params']={r:'85811f6b7cd32eb5',t:'MTcwODM3MzEwNi42NDkwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body></html>
2024-02-19 12:05:06.663 WARNING (SyncWorker_5) [pyaarlo] No locations returned from /hmsdevicemanagement/users/4FRRHW-336-63261314/locations
2024-02-19 12:05:06.663 DEBUG (SyncWorker_5) [pyaarlo] locations=[]`

It then moves on to devices and pulls devices.

**Comment by twrecked** [comment]
It should be trying `https://myapi.arlo.com` . To be sure remove it from both `configuration.yaml` and `aarlo.yaml`. 

The _aarlo_ config in `configuration.yaml` was deprecated in 0.8 but it's still safe to keep around while you're testing.

**Comment by cswinney22** [comment]
> https://my.arlo.com/hmsdevicemanagement/users/4FRRHW-336-63261314/locations

Oh crud. You're right. I was about to say that when I inspect actions via Chrome, I was seeing myapi.arlo.com.
I looked in both and didn't see it in aalo.yaml. So, that's my bad. I'll remove it now and retry. I'll bet that's been the cause the whole time. Standby

**Comment by twrecked** [comment]
It's confusing. Especially upgrading. 

And _Arlo_ is a strange beast because there is a lot of config needed - for a while here I had one machine that needed `send_session` set and another that didn't. So I didn't want to overload the Integrations configurations with the technical pieces.

That said, I still need to upgrade the docs...

**Comment by cswinney22** [comment]
> It's confusing. Especially upgrading.
> 
> And _Arlo_ is a strange beast because there is a lot of config needed - for a while here I had one machine that needed `send_session` set and another that didn't. So I didn't want to overload the Integrations configurations with the technical pieces.
> 
> That said, I still need to upgrade the docs...

I think this is working now. I can arm/disarm from HA and I get the appropriate notifications in my mobile app.
So, this was mainly me carrying the old config over from the old version and forgetting to remove the host id to allow it to use defaults.

By the way, your cloudflare sidesteps are working. I had two servers trying to block me and the third attempt worked. So, I think only people who mess with the integration too much (like me in testing) will run into issues.
