### ISSUE TITLE
Using oauth for authentication

### ISSUE THREAD

**Issue by Moving4407** [twrecked/hass-aarlo#988]
When adding my new Arlo Gen2 essential HD doorbell to Alexa I was redirected to http://oauth.arlo.com/ where I could login with my account and then got a notification through the secure app. Now I get notifications on my Alexa device so it seems there is a different option for authentication. Has this been explored yet or can I help? Seems it would solve a # of issues users are reporting here.

**Comment by twrecked** [comment]
I thought about it in the past - I was using Arlo via IFTTT at the time. I figured there were a couple of things that needed to be done (and my memory could be a little fuzzy here):

- Register as a partner/client/3rd-party-app with Arlo. This will give us a client id to tell them who we are. _I'm not sure how to do this bit._
- Create and host a web page to handle the authentication. We need to do this to keep the client_id secret. _I already host a few pages for things to do with hass-aarlo so this isn't a biggie._
- Hope the APIs are the same, or we can at least use the token with the current APIs. _I'd hope they'd be the same... otherwise it would need a rewrite_

**Comment by Moving4407** [comment]
I’d be happy to reach out to them and ask if that’s ok with you.

**Comment by Moving4407** [comment]
I went ahead and created a topic [here ](https://community.arlo.com/t5/Partner-Integrations/Request-for-a-partner-integration-for-AARLO-a-Home-Assistant/td-p/2419008/jump-to/first-unread-message)on their forum, awaiting their response

**Comment by Moving4407** [comment]
It seems my post was deleted and I got banned. Was worth a try
